var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":105,"id":24,"methods":[{"el":28,"sc":5,"sl":15},{"el":39,"sc":5,"sl":30},{"el":53,"sc":5,"sl":41},{"el":61,"sc":5,"sl":55},{"el":75,"sc":5,"sl":63},{"el":83,"sc":5,"sl":77},{"el":94,"sc":5,"sl":85},{"el":104,"sc":5,"sl":96}],"name":"TripServiceTest","sl":9}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":63}],"name":"when search for all trips for a user, it should return all of them","pass":true,"statements":[{"sl":65},{"sl":68},{"sl":71},{"sl":72},{"sl":73},{"sl":74}]},"test_11":{"methods":[{"sl":41}],"name":"when fetch a trip for id, if the trip exists it should return it","pass":true,"statements":[{"sl":43},{"sl":46},{"sl":49},{"sl":50},{"sl":51},{"sl":52}]},"test_12":{"methods":[{"sl":85}],"name":"when delete a trip from a user, you should be able to delete it","pass":true,"statements":[{"sl":87},{"sl":90},{"sl":93}]},"test_16":{"methods":[{"sl":55}],"name":"when fetch a trip for id, if the trip doesn't exits it shouldn't return it","pass":true,"statements":[{"sl":57},{"sl":60}]},"test_5":{"methods":[{"sl":96}],"name":"when delete a trip for a user, but the user is invalid, it should throw an exception","pass":true,"statements":[{"sl":98},{"sl":101},{"sl":102},{"sl":103}]},"test_7":{"methods":[{"sl":30}],"name":"when create a trip, it should return a complete trip","pass":true,"statements":[{"sl":32},{"sl":35},{"sl":36},{"sl":37},{"sl":38}]},"test_9":{"methods":[{"sl":77}],"name":"when search for all trips for a user, and the user has no trips it should not return nothing.","pass":true,"statements":[{"sl":79},{"sl":82}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [7], [], [7], [], [], [7], [7], [7], [7], [], [], [11], [], [11], [], [], [11], [], [], [11], [11], [11], [11], [], [], [16], [], [16], [], [], [16], [], [], [10], [], [10], [], [], [10], [], [], [10], [10], [10], [10], [], [], [9], [], [9], [], [], [9], [], [], [12], [], [12], [], [], [12], [], [], [12], [], [], [5], [], [5], [], [], [5], [5], [5], [], []]
