var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":123,"id":169,"methods":[{"el":48,"sc":5,"sl":19},{"el":84,"sc":5,"sl":50},{"el":108,"sc":5,"sl":86},{"el":122,"sc":5,"sl":110}],"name":"StayServiceTest","sl":13}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_26":{"methods":[{"sl":50}],"name":"when update an stay for a destination, it should return an updated stay","pass":true,"statements":[{"sl":52},{"sl":64},{"sl":65},{"sl":67},{"sl":73},{"sl":76},{"sl":77},{"sl":78},{"sl":79},{"sl":80},{"sl":81},{"sl":82}]},"test_28":{"methods":[{"sl":110}],"name":"when delete an stay for a destination, but the stay is invalid, it should throw an exception","pass":true,"statements":[{"sl":112},{"sl":113},{"sl":116},{"sl":119},{"sl":120},{"sl":121}]},"test_29":{"methods":[{"sl":86}],"name":"when delete an stay for a destination, but the stay is valid, should be able to delete it","pass":true,"statements":[{"sl":88},{"sl":100},{"sl":101},{"sl":104},{"sl":107}]},"test_8":{"methods":[{"sl":19}],"name":"when create an stay for a destination, it should return the full stay.","pass":true,"statements":[{"sl":21},{"sl":34},{"sl":37},{"sl":40},{"sl":41},{"sl":42},{"sl":43},{"sl":44},{"sl":45},{"sl":46},{"sl":47}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [8], [], [8], [], [], [], [], [], [], [], [], [], [], [], [], [8], [], [], [8], [], [], [8], [8], [8], [8], [8], [8], [8], [8], [], [], [26], [], [26], [], [], [], [], [], [], [], [], [], [], [], [26], [26], [], [26], [], [], [], [], [], [26], [], [], [26], [26], [26], [26], [26], [26], [26], [], [], [], [29], [], [29], [], [], [], [], [], [], [], [], [], [], [], [29], [29], [], [], [29], [], [], [29], [], [], [28], [], [28], [28], [], [], [28], [], [], [28], [28], [28], [], []]
