var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":152,"id":0,"methods":[{"el":18,"sc":5,"sl":14},{"el":33,"sc":5,"sl":23},{"el":35,"sc":5,"sl":35},{"el":44,"sc":5,"sl":37},{"el":57,"sc":5,"sl":46},{"el":71,"sc":5,"sl":59},{"el":92,"sc":5,"sl":73},{"el":104,"sc":5,"sl":94},{"el":116,"sc":5,"sl":106},{"el":128,"sc":5,"sl":118},{"el":140,"sc":5,"sl":130},{"el":151,"sc":5,"sl":142}],"name":"UserServiceTest","sl":12}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_14":{"methods":[{"sl":142}],"name":"when I search for a nonexistent value, it should return an empty list","pass":true,"statements":[{"sl":144},{"sl":147},{"sl":150}]},"test_15":{"methods":[{"sl":46}],"name":"when create a user, but there exists a user with the same email, it should throw an exception","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":51},{"sl":54},{"sl":55},{"sl":56}]},"test_16":{"methods":[{"sl":130}],"name":"when I search by lastName, it returns the users that match","pass":true,"statements":[{"sl":132},{"sl":135},{"sl":138},{"sl":139}]},"test_18":{"methods":[{"sl":59}],"name":"when fetch a user for id, if the user exists it should return it","pass":true,"statements":[{"sl":61},{"sl":64},{"sl":67},{"sl":68},{"sl":69},{"sl":70}]},"test_37":{"methods":[{"sl":106}],"name":"when I search by email, it returns the users that match","pass":true,"statements":[{"sl":108},{"sl":111},{"sl":114},{"sl":115}]},"test_40":{"methods":[{"sl":118}],"name":"when I search by firstName, it returns the users that match","pass":true,"statements":[{"sl":120},{"sl":123},{"sl":126},{"sl":127}]},"test_6":{"methods":[{"sl":94}],"name":"when fetch a user for email, if the user exists it should return it","pass":true,"statements":[{"sl":96},{"sl":99},{"sl":102},{"sl":103}]},"test_7":{"methods":[{"sl":37}],"name":"when create a user, it should return an user with authorities","pass":true,"statements":[{"sl":39},{"sl":42},{"sl":43}]},"test_8":{"methods":[{"sl":73}],"name":"when get a user for email, if the user exists it should return it","pass":true,"statements":[{"sl":75},{"sl":81},{"sl":84},{"sl":87},{"sl":88},{"sl":89},{"sl":90},{"sl":91}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [7], [], [7], [], [], [7], [7], [], [], [15], [], [15], [15], [], [15], [], [], [15], [15], [15], [], [], [18], [], [18], [], [], [18], [], [], [18], [18], [18], [18], [], [], [8], [], [8], [], [], [], [], [], [8], [], [], [8], [], [], [8], [8], [8], [8], [8], [], [], [6], [], [6], [], [], [6], [], [], [6], [6], [], [], [37], [], [37], [], [], [37], [], [], [37], [37], [], [], [40], [], [40], [], [], [40], [], [], [40], [40], [], [], [16], [], [16], [], [], [16], [], [], [16], [16], [], [], [14], [], [14], [], [], [14], [], [], [14], [], []]
