var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":50,"id":716,"methods":[{"el":14,"sc":5,"sl":14},{"el":16,"sc":5,"sl":16},{"el":18,"sc":5,"sl":18},{"el":22,"sc":5,"sl":19},{"el":26,"sc":5,"sl":24},{"el":29,"sc":5,"sl":27},{"el":38,"sc":5,"sl":31},{"el":43,"sc":5,"sl":40},{"el":48,"sc":5,"sl":45}],"name":"Day","sl":10}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":40}],"name":"when create an itinerary for a day, it should return the full itinerary.","pass":true,"statements":[{"sl":41},{"sl":42}]},"test_1":{"methods":[{"sl":14},{"sl":27}],"name":"by subtracting days, the previous destination cannot run out of days\n","pass":true,"statements":[{"sl":28}]},"test_10":{"methods":[{"sl":14},{"sl":24}],"name":"when a trip is added a day to one of its destinations, it should return the updated destination","pass":true,"statements":[{"sl":25}]},"test_16":{"methods":[{"sl":14},{"sl":24}],"name":"when adding days, the next destination cannot run out of days","pass":true,"statements":[{"sl":25}]},"test_19":{"methods":[{"sl":14},{"sl":27}],"name":"hen a trip is subtract a day to one of its destinations, it should return the updated destination","pass":true,"statements":[{"sl":28}]},"test_21":{"methods":[{"sl":40}],"name":"when update an itinerary for a day, it should return an updated itinerary","pass":true,"statements":[{"sl":41},{"sl":42}]},"test_7":{"methods":[{"sl":45}],"name":"when a trip is asked for the total cost, it should return it.","pass":true,"statements":[{"sl":46},{"sl":47}]},"test_8":{"methods":[{"sl":31},{"sl":40}],"name":"when delete an itinerary for a day, but the itinerary is valid, should be able to delete it","pass":true,"statements":[{"sl":32},{"sl":35},{"sl":36},{"sl":37},{"sl":41},{"sl":42}]},"test_9":{"methods":[{"sl":31}],"name":"when delete an itinerary for a day, but the itinerary is invalid, it should throw an exception","pass":true,"statements":[{"sl":32},{"sl":33}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [10, 19, 16, 1], [], [], [], [], [], [], [], [], [], [10, 16], [10, 16], [], [19, 1], [19, 1], [], [], [9, 8], [9, 8], [9], [], [8], [8], [8], [], [], [0, 8, 21], [0, 8, 21], [0, 8, 21], [], [], [7], [7], [7], [], [], []]
