var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":56,"id":839,"methods":[{"el":14,"sc":5,"sl":14},{"el":16,"sc":5,"sl":16},{"el":18,"sc":5,"sl":18},{"el":22,"sc":5,"sl":19},{"el":26,"sc":5,"sl":24},{"el":29,"sc":5,"sl":27},{"el":38,"sc":5,"sl":31},{"el":43,"sc":5,"sl":40},{"el":48,"sc":5,"sl":45},{"el":54,"sc":5,"sl":50}],"name":"Day","sl":10}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":45}],"name":"when a trip is asked for the total cost, it should return it.","pass":true,"statements":[{"sl":46},{"sl":47}]},"test_11":{"methods":[{"sl":40}],"name":"when create an activity for a day, it should return the full activity.","pass":true,"statements":[{"sl":41},{"sl":42}]},"test_12":{"methods":[{"sl":14},{"sl":27}],"name":"hen a trip is subtract a day to one of its destinations, it should return the updated destination","pass":true,"statements":[{"sl":28}]},"test_13":{"methods":[{"sl":31},{"sl":40}],"name":"when delete an activity for a day, but the activity is valid, should be able to delete it","pass":true,"statements":[{"sl":32},{"sl":35},{"sl":36},{"sl":37},{"sl":41},{"sl":42}]},"test_15":{"methods":[{"sl":14},{"sl":24}],"name":"when adding days, the next destination cannot run out of days","pass":true,"statements":[{"sl":25}]},"test_26":{"methods":[{"sl":14},{"sl":27}],"name":"by subtracting days, the previous destination cannot run out of days\n","pass":true,"statements":[{"sl":28}]},"test_3":{"methods":[{"sl":31}],"name":"when delete an activity for a day, but the activity is invalid, it should throw an exception","pass":true,"statements":[{"sl":32},{"sl":33}]},"test_32":{"methods":[{"sl":40}],"name":"when update an activity for a day, it should return an updated activity","pass":true,"statements":[{"sl":41},{"sl":42}]},"test_5":{"methods":[{"sl":14},{"sl":50}],"name":"when a trip is copied, a new trip with the same configuration is returned","pass":true,"statements":[{"sl":51},{"sl":52},{"sl":53}]},"test_9":{"methods":[{"sl":14},{"sl":24}],"name":"when a trip is added a day to one of its destinations, it should return the updated destination","pass":true,"statements":[{"sl":25}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [9, 12, 26, 5, 15], [], [], [], [], [], [], [], [], [], [9, 15], [9, 15], [], [12, 26], [12, 26], [], [], [3, 13], [3, 13], [3], [], [13], [13], [13], [], [], [11, 13, 32], [11, 13, 32], [11, 13, 32], [], [], [1], [1], [1], [], [], [5], [5], [5], [5], [], [], []]
