var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":84,"id":262,"methods":[{"el":17,"sc":5,"sl":9},{"el":26,"sc":5,"sl":19},{"el":35,"sc":5,"sl":28},{"el":44,"sc":5,"sl":37},{"el":55,"sc":5,"sl":46},{"el":65,"sc":5,"sl":57},{"el":75,"sc":5,"sl":67},{"el":83,"sc":5,"sl":77}],"name":"TripTest","sl":7}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_14":{"methods":[{"sl":9}],"name":"when destinations are added to a trip, it must return the updated trip.","pass":true,"statements":[{"sl":11},{"sl":14},{"sl":15},{"sl":16}]},"test_21":{"methods":[{"sl":57}],"name":"when a trip is asked for the destinations without origin, it should return it.","pass":true,"statements":[{"sl":59},{"sl":60},{"sl":63},{"sl":64}]},"test_25":{"methods":[{"sl":28}],"name":"when a trip is asked for the start date, it should return it.","pass":true,"statements":[{"sl":30},{"sl":31},{"sl":34}]},"test_30":{"methods":[{"sl":67}],"name":"when a trip is asked for the total cost, it should return it.","pass":true,"statements":[{"sl":69},{"sl":70},{"sl":73},{"sl":74}]},"test_37":{"methods":[{"sl":19}],"name":"when total days of a trip is requested, it should return the number of days.","pass":true,"statements":[{"sl":21},{"sl":22},{"sl":25}]},"test_40":{"methods":[{"sl":46}],"name":"when a trip is asked for the first destination, it should return it.","pass":true,"statements":[{"sl":48},{"sl":49},{"sl":50},{"sl":53},{"sl":54}]},"test_41":{"methods":[{"sl":77}],"name":"when ask a trip if a destination is not the last, and it is not, it should return true.","pass":true,"statements":[{"sl":79},{"sl":82}]},"test_6":{"methods":[{"sl":37}],"name":"when a trip is asked for the end date, it should return it.","pass":true,"statements":[{"sl":39},{"sl":40},{"sl":43}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [14], [], [14], [], [], [14], [14], [14], [], [], [37], [], [37], [37], [], [], [37], [], [], [25], [], [25], [25], [], [], [25], [], [], [6], [], [6], [6], [], [], [6], [], [], [40], [], [40], [40], [40], [], [], [40], [40], [], [], [21], [], [21], [21], [], [], [21], [21], [], [], [30], [], [30], [30], [], [], [30], [30], [], [], [41], [], [41], [], [], [41], [], []]
