var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":13,"id":344,"methods":[],"name":"TriposoResponse","sl":9},{"el":20,"id":344,"methods":[],"name":"TriposoLocationResponse","sl":16},{"el":26,"id":344,"methods":[],"name":"TriposoAttractionResponse","sl":22},{"el":32,"id":344,"methods":[],"name":"TriposoDayPlannerResponse","sl":28},{"el":49,"id":344,"methods":[],"name":"TriposoLocation","sl":34},{"el":58,"id":344,"methods":[],"name":"TriposoImage","sl":51},{"el":65,"id":344,"methods":[],"name":"TriposoDayPlanner","sl":60},{"el":73,"id":344,"methods":[],"name":"TriposoDay","sl":67},{"el":81,"id":344,"methods":[],"name":"TriposoActivity","sl":75},{"el":122,"id":344,"methods":[{"el":117,"sc":5,"sl":115},{"el":121,"sc":5,"sl":119}],"name":"TriposoPoi","sl":96},{"el":130,"id":358,"methods":[],"name":"TriposoProperty","sl":124},{"el":139,"id":358,"methods":[],"name":"TriposoCoordinates","sl":134},{"el":148,"id":358,"methods":[],"name":"TriposoBookingInfo","sl":141},{"el":157,"id":358,"methods":[],"name":"UnsplashImage","sl":151},{"el":163,"id":358,"methods":[],"name":"UnsplashImageUrl","sl":159},{"el":169,"id":358,"methods":[],"name":"UnsplashResponse","sl":165}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
