var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":13,"id":347,"methods":[],"name":"TriposoResponse","sl":9},{"el":20,"id":347,"methods":[],"name":"TriposoLocationResponse","sl":16},{"el":26,"id":347,"methods":[],"name":"TriposoAttractionResponse","sl":22},{"el":32,"id":347,"methods":[],"name":"TriposoDayPlannerResponse","sl":28},{"el":49,"id":347,"methods":[],"name":"TriposoLocation","sl":34},{"el":58,"id":347,"methods":[],"name":"TriposoImage","sl":51},{"el":65,"id":347,"methods":[],"name":"TriposoDayPlanner","sl":60},{"el":73,"id":347,"methods":[],"name":"TriposoDay","sl":67},{"el":81,"id":347,"methods":[],"name":"TriposoActivity","sl":75},{"el":94,"id":347,"methods":[],"name":"TriposoPoi","sl":83},{"el":109,"id":347,"methods":[],"name":"TriposoAttraction","sl":96},{"el":116,"id":347,"methods":[],"name":"TriposoCoordinates","sl":111},{"el":125,"id":347,"methods":[],"name":"TriposoBookingInfo","sl":118},{"el":134,"id":347,"methods":[],"name":"UnsplashImage","sl":128},{"el":140,"id":347,"methods":[],"name":"UnsplashImageUrl","sl":136},{"el":146,"id":347,"methods":[],"name":"UnsplashResponse","sl":142}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
