name: MyTrips CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test
      run: ./gradlew test
    - name: Run Test Coverage
      run: ./gradlew cloverGenerateReport
    - name: Check test coverage
      id: test-coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      with:
        percentage: "10"
        filename: build/reports/clover/clover.xml
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Coverage'
        status: ${{ steps.coverage.outputs.coverage }}
        path: badges/test-coverage.svg
        color:  ${{
                  steps.coverage.outputs.coverage > 90 && 'green'              ||
                  steps.coverage.outputs.coverage > 80 && 'yellow,green'       ||
                  steps.coverage.outputs.coverage > 70 && 'yellow'             ||
                  steps.coverage.outputs.coverage > 60 && 'orange,yellow'      ||
                  steps.coverage.outputs.coverage > 50 && 'orange'             ||
                  steps.coverage.outputs.coverage > 40 && 'red,orange'         ||
                  steps.coverage.outputs.coverage > 30 && 'red,red,orange'     ||
                  steps.coverage.outputs.coverage > 20 && 'red,red,red,orange' ||
                  'red' }}
    - name: Commit badge
      continue-on-error: true
      env:
        BADGE: ${{ steps.coverage.outputs.path }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add badges/test-coverage.svg
        git commit -m "Update badge"
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ github.token }}
        branch: ${{ steps.coverage.outputs.branch }}

    - name: Deploy report 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: build/reports/clover/html/

    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: mytrips-back
        heroku_email: nnydjesus@gmail.com


